version: '3'
services:
  meowai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meowai
    environment:
      - user=USERNAME
      - pwd=PASSWORD
      - mode=share
      - lang=zh
      - ip=127.0.0.1:5000
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/MeowAI/docker/data
      - ./data/.paddleocr:/root/.paddleocr
      - ./data/.paddleclas:/root/.paddleclas
    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]